[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vfd_providers"
dynamic = ["version"]
description = "VFD Providers"
authors = [
    {name = "ERP Champions Ltd", email = "devops@erpchampions.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.urls]
Homepage = "https://github.com/erpchampions/vfd_providers"

[tool.setuptools.dynamic]
version = {attr = "vfd_providers.__version__"}

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"

[tool.bench.dev-dependencies]
